networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
services:
  mongodb:
    image: 172.22.255.22:5000/mongodb
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./volumes/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  flask:
    image: 172.22.255.22:5000/frepair_flask
    container_name: flaskimage
    volumes:
      - ./volumes/Flask/storage:/storage
      - ./volumes/Flask/static:/app/static
      - ./volumes/Flask/templates:/app/templates
      - ./volumes/Flask/conf:/app/conf
      - ./volumes/Flask/src:/app
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 5001:5000
    networks:
      - frontend
      - backend

  nginx:
    image: 172.22.255.22:5000/frepair_nginx
    container_name: nginx
    depends_on:
      - flask
    links:
      - flask
    ports:
      - 8088:80
    volumes:
      - ./volumes/nginx/html:/var/share/nginx
      - ./volumes/nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - frontend
      - backend       