networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
services:
  mongodb:
    image: ${IMAGE_MONGODB}
    container_name: ${CONTAINER_MONGODB}
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=CooperExposure
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ${VOLUMES_MONGODB}:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  flask:
    image: ${IMAGE_FLASK}
    build: ${BUILD_FLASK}
    container_name: ${CONTAINER_FLASK}
    volumes:
      - ${VOLUMES_FLASK_STATIC}:/app/static
      - ${VOLUMES_FLASK_TEMPLATES}:/app/templates
      - ${VOLUMES_FLASK_CONF}:/app/conf
      - ${VOLUMES_FLASK_SRC}:/app
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 5000:5000
    networks:
      - frontend
      - backend

  nginx:
    image: ${IMAGE_NGINX}
    build: ${BUILD_NGINX}
    container_name: ${CONTAINER_NGINX}
    depends_on:
      - flask
    links:
      - flask
    ports:
      - 80:80
    volumes:
      - ${VOLUMES_NGINX_SHARE}:/var/share/nginx
      - ${VOLUMES_NGINX_LOG}:/var/log/nginx
    networks:
      - frontend
      - backend       
